server:
  port: 7014
spring:
  application:
    name: webmail-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
  redis:
    # 地址
    host: 192.168.0.101
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
