spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.101:3306/webmail-pms
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GEKp6NkYmVTwDVYZbHL   #配置阿里云oss 子账户密码
      secret-key: 4Re1sr9fOdbPmvbqxYxvDNG9iOWytB
      oss:
        endpoint: http://oss-cn-shenzhen.aliyuncs.com  #配置endpoint
  application:
    name: product-provider
  http:
      encoding:
        force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    # 地址
    host: 192.168.0.101
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
  # spring-cache 使用redis作为缓存
  cache:
    type: redis
    redis:
      time-to-live: 360000
      #如果没指定前缀,则使用缓存名字
      use-key-prefix: true
      #是否缓存空值
      cache-null-values: true
  session:
    store-type: redis
mybatis-plus:
  mapper-locations: classpath:mapper/product/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-value: 1  #已删除
      logic-not-delete-value: 0 #未删除
server:
  port: 7003
logging:
  level:
    com.zy.webmail: debug

